//! The *internal* sandbox configuration.
//!
//! This module is deliberately separate from the spec-file view (the
//! sibling modules `file`, `hostfs`, `net` and `tmpfs`): these are the
//! types the sandbox machinery — `crate::sandbox`, `crate::hostfs` and
//! `crate::netns` — actually runs with. Nothing here is ever
//! (de)serialized from the spec file: the config-file types are compiled
//! down into these by [`SandboxConfig::compile`].

use std::path::PathBuf;

use super::Spec;
use super::net::NetConfig;
use super::tmpfs::TmpfsPerms;

/// The sandbox's internal network configuration: what [`crate::netns`]
/// runs with, compiled down from the spec file's [`NetConfig`].
#[derive(Debug, Clone, PartialEq)]
pub struct Net {
    /// Run the command in a fresh network namespace behind a proxy.
    pub isolated: bool,
    /// The proxy allow-list; empty means: allow everything.
    pub allow: Vec<String>,
}

impl From<&NetConfig> for Net {
    fn from(net: &NetConfig) -> Net {
        Net {
            isolated: net.isolated,
            allow: net.allow.clone(),
        }
    }
}

/// The sandbox's *internal* configuration: the compiled-down form of the
/// spec file, and everything the sandbox machinery consumes. The
/// config-file view is [`Spec`]; this is what [`crate::sandbox`],
/// [`crate::hostfs`] and [`crate::netns`] see.
#[derive(Debug, PartialEq)]
pub struct SandboxConfig {
    /// The filesystem setup operations: all of them are generated by the
    /// `hostfs` mappings, in mapping order (see [`Spec::hostfs`]).
    pub ops: Vec<Op>,
    /// The internal network configuration.
    pub net: Net,
    /// The hostfs pattern → permission list backing the FUSE filesystem.
    pub patterns: Patterns,
}

impl SandboxConfig {
    /// Compile a parsed spec file down into the internal configuration.
    ///
    /// The filesystem ops are the ops the `hostfs.mappings` stand for,
    /// applied in mapping order: the mount-point mappings (`dev`,
    /// `tmpfs`, `proc` and `bind` — see
    /// [`crate::spec::hostfs::HostFsConfig::ops`]) and the `symlink`
    /// mappings each contribute their op.
    ///
    /// Nothing is mounted automatically — in particular, procfs is only
    /// mounted when the spec says so: a `proc` mapping chooses where (and
    /// whether at all) a fresh procfs instance appears.
    pub fn compile(spec: &Spec) -> SandboxConfig {
        SandboxConfig {
            ops: spec.hostfs.ops(),
            net: Net::from(&spec.net),
            patterns: spec.hostfs.patterns(),
        }
    }
}

impl Op {
    /// One-line human description of the op: what it does and where. Used
    /// by `rs-bubble ls` to show the mount/symlink "actions" the config
    /// performs.
    pub fn describe(&self) -> String {
        match self {
            Op::Bind { src, dest } => {
                if src == &dest.to_string_lossy() {
                    format!("bind   {src}")
                } else {
                    format!("bind   {src} -> {}", dest.display())
                }
            }
            Op::Symlink { src, dest } => format!("symlink {} -> {src}", dest.display()),
            Op::Proc { dest } => format!("procfs at {}", dest.display()),
            Op::Dev { dest } => format!("minimal dev at {}", dest.display()),
            Op::Tmpfs {
                dest,
                perms,
                size,
            } => {
                let mut detail = String::new();
                if let Some(perms) = perms {
                    detail.push_str(&format!(" perms={:04o}", perms.0));
                }
                if let Some(size) = size {
                    detail.push_str(&format!(" size={size}"));
                }
                format!("tmpfs  {}{detail}", dest.display())
            }
        }
    }
}

/// One sandbox setup operation, applied inside the sandbox in list order
/// (order matters, exactly like bwrap). Purely internal: the spec file
/// expresses all of these through `hostfs` mappings — see
/// [`crate::spec::hostfs::Mapping::op`].
#[derive(Debug, Clone, PartialEq)]
pub enum Op {
    Bind {
        src: String,
        dest: PathBuf,
    },
    Symlink {
        src: String,
        dest: PathBuf,
    },
    /// Mount a fresh procfs instance. Produced by a `proc` mapping, and
    /// kept here so the sandbox can treat all ops uniformly.
    Proc {
        dest: PathBuf,
    },
    /// Mount a minimal `/dev`, like bwrap's `--dev`: a fresh tmpfs (mode
    /// 0755, `MS_NOSUID|MS_NODEV`) populated with the usual device nodes
    /// (`null`, `zero`, `full`, `random`, `urandom`, `tty`), the stdio
    /// symlinks, `/dev/shm`, a fresh devpts instance at `pts` plus the
    /// `ptmx` symlink, and `/dev/console` bound to the host tty when stdin
    /// is one.
    Dev {
        dest: PathBuf,
    },
    /// Mount a fresh tmpfs instance, like bwrap's `--tmpfs`. Options mirror
    /// bwrap: `perms` is the octal mode of the mount root (default 0755) and
    /// `size` the maximum size in bytes (default: unlimited/half of RAM).
    /// The mount is made with `MS_NOSUID | MS_NODEV`, like bwrap's.
    Tmpfs {
        dest: PathBuf,
        /// Octal mode, e.g. `"0755"` or `755`. Default: 0755.
        perms: Option<TmpfsPerms>,
        /// Maximum tmpfs size in bytes.
        size: Option<u64>,
    },
}

/// The permission a hostfs pattern grants inside the sandbox: the
/// internal representation of a mapping's `type` (see
/// [`crate::spec::hostfs::Mapping`]).
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum Permission {
    /// The matched paths are mirrored into the sandbox **read-only**: they can
    /// be read (and executed, when the underlying file or directory has the
    /// exec bits), but never modified.
    Ro,
    /// The matched paths are mirrored into the sandbox **read-write**: they can
    /// also be modified, created or deleted — as far as the underlying host
    /// file or directory really allows it (the real permissions apply).
    Rw,
    /// The matched paths are hidden. A hidden **directory** hides its
    /// whole subtree, too.
    Hide,
    /// The matched paths are exposed **empty**: as an empty, unwritable
    /// directory when the path is (or would be) a directory, or as an
    /// empty file when it matches a real file. Nothing below an empty
    /// path is visible. Meant as mount points inside the sandbox, e.g.
    /// `/dev`, `/tmp`, `/proc`.
    Empty,
}

impl Permission {
    /// Whether the permission mirrors real host content (`ro` or `rw`).
    pub fn is_mirrored(self) -> bool {
        matches!(self, Permission::Ro | Permission::Rw)
    }

    /// Whether the permission additionally allows writing (`rw` only).
    pub fn is_writable(self) -> bool {
        self == Permission::Rw
    }
}

impl std::fmt::Display for Permission {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Permission::Ro => "ro",
            Permission::Rw => "rw",
            Permission::Hide => "hide",
            Permission::Empty => "empty",
        })
    }
}

/// The internal `hostfs` representation: an *ordered* list of
/// (glob pattern, permission) pairs — the compiled-down form of the
/// spec's [`crate::spec::hostfs::Mapping`] list. That order matters: when
/// a path matches several patterns, the **last** matching pattern decides.
#[derive(Debug, Default, PartialEq, Clone)]
pub struct Patterns(pub Vec<(String, Permission)>);

impl Patterns {
    /// The pattern/permission pairs, in spec order.
    pub fn iter(&self) -> impl Iterator<Item = &(String, Permission)> {
        self.0.iter()
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}
